# Generated by Django 4.2.24 on 2025-09-16 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("fall", "Fall"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("name", models.CharField(default="My Schedule", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "semester", "name"],
                "unique_together": {("student", "semester", "year", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="courses.courseoffering",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "offering__course__department__code",
                    "offering__course__course_number",
                ],
                "unique_together": {("schedule", "offering")},
            },
        ),
        migrations.CreateModel(
            name="DegreeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "degree_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="courses.degreeprogram",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degree_audits",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "degree_program")},
            },
        ),
    ]
