# Generated by Django 4.2.24 on 2025-09-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degreeaudit",
            options={"ordering": ["-last_updated"]},
        ),
    ]
