# Generated by Django 4.2.24 on 2025-10-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20250916_0612"),
        ("courses", "0008_alter_program_department"),
        ("schedules", "0004_fix_program_foreign_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Grade received (e.g., A+, A, B+)",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "semester_taken",
                    models.CharField(
                        blank=True,
                        help_text="Semester when taken (e.g., Fall 2024)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this course"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_selections",
                        to="courses.course",
                    ),
                ),
                (
                    "degree_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_selections",
                        to="schedules.degreeaudit",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_selections",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("student", "course", "degree_audit")},
            },
        ),
    ]
