# Generated by Django 4.2.24 on 2025-10-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_usercourseselection"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourseselection",
            name="timetable_box_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the timetable box this course belongs to",
                max_length=100,
                null=True,
            ),
        ),
    ]
