# Generated by Django 4.2.24 on 2025-09-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="antirequisites",
            field=models.ManyToManyField(
                blank=True, related_name="antirequisite_for", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="corequisites",
            field=models.ManyToManyField(
                blank=True, related_name="corequisite_for", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="restricted_to_majors",
            field=models.ManyToManyField(
                blank=True,
                related_name="restricted_courses",
                to="courses.degreeprogram",
            ),
        ),
    ]
