# Generated by Django 4.2.24 on 2025-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_antirequisites_course_corequisites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
