# Generated by Django 4.2.24 on 2025-09-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="terms_offered",
            field=models.JSONField(
                default=list,
                help_text="List of terms when course is offered (fall, winter, spring)",
            ),
        ),
        migrations.CreateModel(
            name="PrerequisiteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this prerequisite group (e.g., 'Statistics Requirement')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this group represents",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this group is required or optional",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_groups",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "name"],
            },
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prerequisites",
                to="courses.prerequisitegroup",
            ),
        ),
    ]
