# Generated by Django 4.2.24 on 2025-09-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_terms_offered_prerequisitegroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_overall_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Minimum overall average required",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "minimum_major_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Minimum major average required",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "total_credits_required",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("co_op_available", models.BooleanField(default=False)),
                ("honours_available", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="courses.department",
                    ),
                ),
            ],
            options={
                "ordering": ["program_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProgramType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("joint_major", "Joint Major"),
                            ("honours", "Honours"),
                            ("specialization", "Specialization"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("required_courses", "Required Courses"),
                            ("elective_courses", "Elective Courses"),
                            ("credit_requirement", "Credit Requirement"),
                            ("average_requirement", "Average Requirement"),
                            ("course_group", "Course Group"),
                            ("subject_requirement", "Subject Requirement"),
                            ("level_requirement", "Level Requirement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "credits_required",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "courses_required",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum course level (e.g., 200, 300, 400)",
                        null=True,
                    ),
                ),
                (
                    "maximum_courses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum courses from same subject",
                        null=True,
                    ),
                ),
                (
                    "subject_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="Allowed subject codes"
                    ),
                ),
                (
                    "excluded_subject_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="Excluded subject codes"
                    ),
                ),
                (
                    "require_different_subjects",
                    models.BooleanField(
                        default=False,
                        help_text="Require courses from different subjects",
                    ),
                ),
                (
                    "minimum_subjects",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of different subjects"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_requirements",
                        to="courses.programrequirement",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProgramConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("substitution", "Course Substitution"),
                            ("exclusion", "Course Exclusion"),
                            ("prerequisite_override", "Prerequisite Override"),
                            ("credit_limit", "Credit Limit"),
                            ("cross_listing", "Cross-listing Restriction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "affected_courses",
                    models.JSONField(
                        default=list, help_text="List of course IDs affected"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions for the constraint"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "constraint_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="program_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="courses.programtype",
            ),
        ),
        migrations.CreateModel(
            name="ProgramCourseRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this specific course is required",
                    ),
                ),
                (
                    "is_alternative",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an alternative to other courses",
                    ),
                ),
                (
                    "alternative_group",
                    models.CharField(
                        blank=True,
                        help_text="Group name for alternative courses",
                        max_length=100,
                    ),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True, help_text="Minimum grade required", max_length=5
                    ),
                ),
                (
                    "maximum_credits",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_requirements",
                        to="courses.course",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_requirements",
                        to="courses.programrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement", "order", "course"],
                "unique_together": {("requirement", "course")},
            },
        ),
    ]
