# Generated by Django 4.2.24 on 2025-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_program_programtype_programrequirement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degreeprogram",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="degreeprogram",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_course_title"
            ),
        ),
    ]
