# Generated by Django 4.2.24 on 2025-10-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_add_unique_name_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course_title",
        ),
    ]
