# Generated by Django 4.2.24 on 2025-10-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_remove_unique_title_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="courses.department",
            ),
        ),
    ]
