# Generated by Django 4.2.24 on 2025-09-16 06:12

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_user(apps, schema_editor):
    """Create the fixed admin user and guest user"""
    # Create or get the admin user
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@uniplanner.edu',
            'first_name': 'System',
            'last_name': 'Administrator',
            'is_staff': True,
            'is_superuser': True,
        }
    )
    
    # Always set the password to admin123 (in case it was changed)
    admin_user.set_password('admin123')
    admin_user.save()
    
    # Create or get the admin profile
    UserProfile = apps.get_model('users', 'UserProfile')
    admin_profile, profile_created = UserProfile.objects.get_or_create(
        user_id=admin_user.id,
        defaults={
            'role': 'admin',
            'phone': '',
            'address': 'System Administrator',
        }
    )
    
    # Ensure the profile is set to admin role
    if admin_profile.role != 'admin':
        admin_profile.role = 'admin'
        admin_profile.save()
    
    # Remove any student profile if it exists (admin shouldn't have one)
    StudentProfile = apps.get_model('users', 'StudentProfile')
    try:
        student_profile = admin_user.student_profile
        student_profile.delete()
    except StudentProfile.DoesNotExist:
        pass
    
    # Create or get the guest user
    guest_user, guest_created = User.objects.get_or_create(
        username='guest',
        defaults={
            'email': 'guest@uniplanner.edu',
            'first_name': 'Guest',
            'last_name': 'User',
            'is_staff': False,
            'is_superuser': False,
        }
    )
    
    # Always set the password to guest123 (in case it was changed)
    guest_user.set_password('guest123')
    guest_user.save()
    
    # Create or get the guest profile
    guest_profile, guest_profile_created = UserProfile.objects.get_or_create(
        user_id=guest_user.id,
        defaults={
            'role': 'student',
            'phone': '',
            'address': 'Guest User',
        }
    )
    
    # Ensure the profile is set to student role
    if guest_profile.role != 'student':
        guest_profile.role = 'student'
        guest_profile.save()
    
    # Create or get the guest student profile
    guest_student_profile, guest_student_created = StudentProfile.objects.get_or_create(
        user_id=guest_user.id,
        defaults={
            'student_id': 'GUEST001',
            'graduation_year': 2025,
            'gpa': 3.5,
            'total_credits_earned': 0,
            'enrollment_status': 'active',
        }
    )


def reverse_create_admin_user(apps, schema_editor):
    """Remove the admin and guest users (optional - you might not want to do this)"""
    User = apps.get_model('auth', 'User')
    try:
        admin_user = User.objects.get(username='admin')
        admin_user.delete()
    except User.DoesNotExist:
        pass
    
    try:
        guest_user = User.objects.get(username='guest')
        guest_user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile_enrollment_status_userprofile"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
